### PR TITLE
eu-legal additions

### PR DESCRIPTION
**Pull request by jBangiev**

### CODE REVIEW

**Comment by jBangiev** [comment]
updated

**Comment by Quetzacoalt91** [comment]
Hi,

My bad, the argument of ```$this->isPaymentPossible()``` throws a notice. Can you remove it please ?

The picture you use does not exist. Can you change the file name or add *hipay_eu.png* ?

**Comment by jBangiev** [comment]
updated

**Comment by Quetzacoalt91** [comment]
Hi,

Your PR has just been merged and the EU-legal changes should be available from tomorrow.

Regards

**Pull request merged**
